// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwvgTAALxUrPV1b4JqckRuMF9cGYSrIQ',
    appId: '1:160957435420:web:0c6ce5cb03a4bfabcb99d9',
    messagingSenderId: '160957435420',
    projectId: 'personalexpense-d7196',
    authDomain: 'personalexpense-d7196.firebaseapp.com',
    storageBucket: 'personalexpense-d7196.appspot.com',
    measurementId: 'G-NEETFN486C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGcrKDqchuYo8h8JRnpax2L1REaFvZFs',
    appId: '1:160957435420:android:70179c3a7fe4af72cb99d9',
    messagingSenderId: '160957435420',
    projectId: 'personalexpense-d7196',
    storageBucket: 'personalexpense-d7196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDox531jtJLwyRwKzv38WDlhXqm0JwQlTk',
    appId: '1:160957435420:ios:935baa33d8abc335cb99d9',
    messagingSenderId: '160957435420',
    projectId: 'personalexpense-d7196',
    storageBucket: 'personalexpense-d7196.appspot.com',
    iosClientId:
        '160957435420-ed0hhe2i9stc3eutn3qhmgh458dhh9b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.exApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDox531jtJLwyRwKzv38WDlhXqm0JwQlTk',
    appId: '1:160957435420:ios:935baa33d8abc335cb99d9',
    messagingSenderId: '160957435420',
    projectId: 'personalexpense-d7196',
    storageBucket: 'personalexpense-d7196.appspot.com',
    iosClientId:
        '160957435420-ed0hhe2i9stc3eutn3qhmgh458dhh9b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.exApp',
  );
}
